categories:
- Sequence Analysis
description: Convert selected fields from TBProfiler json output to tabular
homepage_url: https://github.com/public-health-bioinformatics/galaxy_tools/blob/master/tools/tbprofiler_json_to_tabular
long_description: |
  Convert selected fields from TBProfiler json output to tabular
name: tbprofiler_json_to_tabular
owner: public-health-bioinformatics
remote_repository_url: https://github.com/public-health-bioinformatics/galaxy_tools/blob/master/tools/tbprofiler_json_to_tabular
type: unrestricted
